## updateOrganizationLoginSecurity # Update the login security settings for an organization
# https://developer.cisco.com/meraki/api-v1/#!update-organization-login-security

function updateOrganizationLoginSecurity ()
{
    # Verify function requirements
    for req in curl; do
        type  >/dev/null 2>&1 || {
            echo >&2 "$(basename "${0}" 2> /dev/null):${FUNCNAME[0]} - ${req} is not installed. Aborting."
            exit 1
        }
    done

    if [[ -z "${meraki_uri}" ]] || [[ -z "${auth_key}" ]] || [[ -z "${2}" ]]; then
	cat <<-EOF
	$(basename "${0}" 2> /dev/null):${FUNCNAME[0]} - Update the login security settings for an organization
	Ref: https://developer.cisco.com/meraki/api-v1/#!update-organization-login-security
	---
	Meraki API Base URI: \${meraki_uri} (${meraki_uri:-required})
	API Authorization Key: \${auth_key} (${auth_key:-required})
	organizationId: \${1} (${1:-required})
	---
	enforcePasswordExpiration: Boolean indicating whether users are forced to change their password every X number of days.
	passwordExpirationDays: Number of days after which users will be forced to change their password.
	enforceDifferentPasswords: Boolean indicating whether users, when setting a new password, are forced to choose a new password that is different from any past passwords.
	numDifferentPasswords: Number of recent passwords that new password must be distinct from.
	enforceStrongPasswords: Boolean indicating whether users will be forced to choose strong passwords for their accounts. Strong passwords are at least 8 characters that contain 3 of the following: number, uppercase letter, lowercase letter, and symbol
	enforceAccountLockout: Boolean indicating whether users' Dashboard accounts will be locked out after a specified number of consecutive failed login attempts.
	accountLockoutAttempts: Number of consecutive failed login attempts after which users' accounts will be locked.
	enforceIdleTimeout: Boolean indicating whether users will be logged out after being idle for the specified number of minutes.
	idleTimeoutMinutes: Number of minutes users can remain idle before being logged out of their accounts.
	enforceTwoFactorAuth: Boolean indicating whether users in this organization will be required to use an extra verification code when logging in to Dashboard. This code will be sent to their mobile phone via SMS, or can be generated by the authenticator application.
	enforceLoginIpRanges: Boolean indicating whether organization will restrict access to Dashboard (including the API) from certain IP addresses.
	loginIpRanges: List of acceptable IP ranges. Entries can be single IP addresses, IP address ranges, and CIDR subnets.
	apiAuthentication: Details for indicating whether organization will restrict access to API (but not Dashboard) to certain IP addresses.
	EOF
    else
        ### PLACEHOLDER cURL - FIX ME ###
        echo curl --silent --output /dev/null --write-out "%{http_code}\n" --location \
          --request PUT --url "${meraki_uri}/organizations/${1}/loginSecurity" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --header "X-Cisco-Meraki-API-Key: ${auth_key}" \
	  --data "${2}"
    fi
}
